/*
###############################################################
#  Generated by:      Cadence Encounter 14.13-s036_1
#  OS:                Linux x86_64(Host ID ssh-soc)
#  Generated on:      Thu Nov 21 14:31:19 2019
#  Design:            credit_card_payment_fsm_map
#  Command:           saveNetlist credit_card_payment_fsm_map.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 14.13-s036_1
#  OS:                Linux x86_64(Host ID ssh-soc)
#  Generated on:      Wed Nov 20 13:44:21 2019
#  Design:            credit_card_payment_fsm_map
#  Command:           saveDesign credit_card_payment_fsm_map.enc
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 14.13-s036_1
#  OS:                Linux x86_64(Host ID ssh-soc)
#  Generated on:      Wed Nov 20 13:34:07 2019
#  Design:            credit_card_payment_fsm_map
#  Command:           saveDesign credit_card_payment_fsm_map.enc
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 14.13-s036_1
#  OS:                Linux x86_64(Host ID ssh-soc)
#  Generated on:      Wed Nov 20 13:10:25 2019
#  Design:            credit_card_payment_fsm_map
#  Command:           saveDesign credit_card_payment_fsm_map.enc
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1
// Verification Directory fv/credit_card_payment_fsm 
module credit_card_payment_fsm_map (
	clk, 
	reset, 
	process_init, 
	visa_choice_in, 
	mastercard_choice_in, 
	amex_choice_in, 
	pymt_amt_conf, 
	pymt_amt_denied, 
	pin_fail, 
	pin_success, 
	transaction_fail, 
	transaction_success, 
	light_bit, 
	card_choice, 
	pymt_amt_print, 
	pin_process_init, 
	pymt_process_init, 
	process_abort);
   input clk;
   input reset;
   input process_init;
   input visa_choice_in;
   input mastercard_choice_in;
   input amex_choice_in;
   input pymt_amt_conf;
   input pymt_amt_denied;
   input pin_fail;
   input pin_success;
   input transaction_fail;
   input transaction_success;
   output light_bit;
   output [1:0] card_choice;
   output pymt_amt_print;
   output pin_process_init;
   output pymt_process_init;
   output process_abort;

   // Internal wires
   wire [10:0] state;
   wire [1:0] fail_counter;
   wire n_2;
   wire n_4;
   wire n_6;
   wire n_8;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_112;
   wire n_113;
   wire n_114;

   DFFHQX1 \state_reg[7]  (.Q(state[7]),
	.D(n_99),
	.CK(clk));
   DFFHQX1 \state_reg[9]  (.Q(state[9]),
	.D(n_98),
	.CK(clk));
   NAND3BXL g2972 (.Y(n_99),
	.C(n_94),
	.B(n_68),
	.AN(n_81));
   DFFHQX1 \state_reg[6]  (.Q(state[6]),
	.D(n_97),
	.CK(clk));
   DFFHQX1 \state_reg[8]  (.Q(state[8]),
	.D(n_96),
	.CK(clk));
   OR2XL g2983 (.Y(n_98),
	.B(n_93),
	.A(n_95));
   NAND3BXL g2973 (.Y(n_97),
	.C(n_89),
	.B(n_76),
	.AN(n_46));
   OR4X1 g2976 (.Y(n_96),
	.D(n_86),
	.C(n_84),
	.B(n_95),
	.A(n_45));
   NOR4X1 g2975 (.Y(n_94),
	.D(n_114),
	.C(n_88),
	.B(n_61),
	.A(n_67));
   DFFHQX1 \state_reg[0]  (.Q(state[0]),
	.D(n_87),
	.CK(clk));
   DFFHQX1 \fail_counter_reg[0]  (.Q(fail_counter[0]),
	.D(n_90),
	.CK(clk));
   OAI211X1 g2991 (.Y(n_93),
	.C0(n_71),
	.B0(n_92),
	.A1(n_56),
	.A0(n_4));
   DFFQXL \fail_counter_reg[1]  (.Q(fail_counter[1]),
	.D(n_83),
	.CK(clk));
   INVX1 g2995 (.Y(n_92),
	.A(n_114));
   NOR2BX1 g2986 (.Y(n_90),
	.B(reset),
	.AN(n_80));
   NOR4X1 g2977 (.Y(n_89),
	.D(n_95),
	.C(n_88),
	.B(n_64),
	.A(n_40));
   DFFHQX1 \state_reg[10]  (.Q(state[10]),
	.D(n_77),
	.CK(clk));
   DFFHQX1 \state_reg[2]  (.Q(state[2]),
	.D(n_79),
	.CK(clk));
   OAI2BB1X1 g2989 (.Y(n_87),
	.B0(n_82),
	.A1N(n_70),
	.A0N(pymt_amt_denied));
   OAI22X1 g2990 (.Y(n_86),
	.B1(n_85),
	.B0(pymt_amt_denied),
	.A1(n_55),
	.A0(n_65));
   OAI21X1 g2997 (.Y(n_84),
	.B0(n_48),
	.A1(n_60),
	.A0(transaction_fail));
   NOR2X1 g2987 (.Y(n_83),
	.B(n_75),
	.A(reset));
   DFFHQX1 \state_reg[5]  (.Q(state[5]),
	.D(n_72),
	.CK(clk));
   DFFHQX1 \state_reg[4]  (.Q(state[4]),
	.D(n_69),
	.CK(clk));
   AOI22X1 g2998 (.Y(n_82),
	.B1(n_57),
	.B0(n_78),
	.A1(n_81),
	.A0(transaction_fail));
   OAI31X1 g2999 (.Y(n_80),
	.B0(n_62),
	.A2(n_51),
	.A1(fail_counter[0]),
	.A0(n_74));
   OAI2BB1X1 g3000 (.Y(n_79),
	.B0(n_63),
	.A1N(n_78),
	.A0N(n_54));
   OAI211X1 g2988 (.Y(n_77),
	.C0(n_73),
	.B0(n_53),
	.A1(n_76),
	.A0(n_6));
   DFFHQX1 \state_reg[1]  (.Q(state[1]),
	.D(n_59),
	.CK(clk));
   MXI2XL g3001 (.Y(n_75),
	.S0(n_74),
	.B(fail_counter[1]),
	.A(n_52));
   OAI31X1 g2985 (.Y(n_88),
	.B0(n_73),
	.A2(state[7]),
	.A1(n_44),
	.A0(reset));
   INVX1 g3003 (.Y(n_72),
	.A(n_71));
   INVX1 g3006 (.Y(n_85),
	.A(n_70));
   INVX1 g3011 (.Y(n_69),
	.A(n_68));
   OR2X1 g2994 (.Y(n_95),
	.B(n_67),
	.A(n_66));
   DFFHQX1 \state_reg[3]  (.Q(state[3]),
	.D(n_66),
	.CK(clk));
   NAND2X1 g3004 (.Y(n_71),
	.B(n_64),
	.A(n_65));
   NOR2X1 g3007 (.Y(n_70),
	.B(n_76),
	.A(pymt_amt_conf));
   NAND2BX1 g3009 (.Y(n_63),
	.B(pymt_amt_conf),
	.AN(n_76));
   NAND2XL g3010 (.Y(n_62),
	.B(fail_counter[0]),
	.A(n_74));
   OAI21X1 g3012 (.Y(n_68),
	.B0(n_64),
	.A1(n_2),
	.A0(visa_choice_in));
   NOR3BX1 g3013 (.Y(n_61),
	.C(pin_success),
	.B(pin_fail),
	.AN(n_78));
   INVX1 g3015 (.Y(n_60),
	.A(n_81));
   NOR2BX1 g3017 (.Y(n_59),
	.B(n_31),
	.AN(n_78));
   NOR2X1 g3016 (.Y(n_81),
	.B(n_56),
	.A(transaction_success));
   INVX1 g3020 (.Y(n_55),
	.A(n_64));
   AOI32X2 g3025 (.Y(n_74),
	.B1(n_41),
	.B0(n_54),
	.A2(n_29),
	.A1(n_49),
	.A0(state[10]));
   NOR2BX1 g3027 (.Y(n_66),
	.B(n_42),
	.AN(n_47));
   NOR2X1 g3028 (.Y(n_78),
	.B(state[8]),
	.A(n_53));
   NOR2X1 g3029 (.Y(n_52),
	.B(n_51),
	.A(n_11));
   NOR3X2 g3021 (.Y(n_64),
	.C(n_43),
	.B(state[7]),
	.A(n_50));
   NAND3BX2 g3022 (.Y(n_76),
	.C(n_49),
	.B(state[7]),
	.AN(n_50));
   OAI211X1 g3023 (.Y(n_48),
	.C0(n_26),
	.B0(n_39),
	.A1(n_47),
	.A0(n_32));
   NAND2X1 g3026 (.Y(n_56),
	.B(state[8]),
	.A(n_46));
   NOR4BBX1 g3005 (.Y(n_67),
	.D(state[10]),
	.C(state[1]),
	.BN(state[3]),
	.AN(n_34));
   NOR2X1 g3008 (.Y(n_73),
	.B(n_45),
	.A(n_112));
   OR4X1 g3019 (.Y(n_44),
	.D(n_43),
	.C(state[10]),
	.B(state[6]),
	.A(n_30));
   NAND2X1 g3031 (.Y(n_50),
	.B(state[8]),
	.A(n_47));
   AOI33X2 g3032 (.Y(n_42),
	.B2(n_17),
	.B1(state[8]),
	.B0(state[7]),
	.A2(n_24),
	.A1(state[5]),
	.A0(state[9]));
   INVX1 g3033 (.Y(n_53),
	.A(n_46));
   INVX1 g3036 (.Y(n_51),
	.A(n_41));
   NOR3X1 g3034 (.Y(n_46),
	.C(n_36),
	.B(n_37),
	.A(n_38));
   NOR3BX1 g3035 (.Y(n_40),
	.C(n_43),
	.B(n_38),
	.AN(n_39));
   NOR4X1 g3037 (.Y(n_41),
	.D(n_36),
	.C(n_28),
	.B(n_37),
	.A(n_21));
   NOR4BX1 g3024 (.Y(n_45),
	.D(n_36),
	.C(state[3]),
	.B(n_33),
	.AN(state[1]));
   NOR2BX1 g3030 (.Y(n_34),
	.B(n_33),
	.AN(n_49));
   NOR2X1 g3038 (.Y(n_47),
	.B(state[10]),
	.A(n_38));
   NOR2X1 g3039 (.Y(n_32),
	.B(n_38),
	.A(n_31));
   NAND3BXL g3040 (.Y(n_30),
	.C(n_25),
	.B(process_init),
	.AN(state[0]));
   NOR2X1 g3043 (.Y(n_29),
	.B(n_28),
	.A(n_22));
   NAND3X1 g3041 (.Y(n_33),
	.C(n_37),
	.B(state[8]),
	.A(n_27));
   NAND2X1 g3044 (.Y(n_38),
	.B(n_14),
	.A(n_27));
   NAND2X1 g3047 (.Y(n_36),
	.B(n_26),
	.A(state[10]));
   INVX1 g3048 (.Y(n_28),
	.A(n_25));
   OAI31X1 g3052 (.Y(n_24),
	.B0(n_20),
	.A2(state[7]),
	.A1(state[8]),
	.A0(state[4]));
   NOR2X1 g3049 (.Y(n_25),
	.B(n_113),
	.A(state[2]));
   AOI31X1 g3050 (.Y(n_22),
	.B0(n_18),
	.A2(state[7]),
	.A1(state[0]),
	.A0(state[6]));
   NOR3BX1 g3046 (.Y(n_54),
	.C(n_57),
	.B(pin_success),
	.AN(pin_fail));
   NOR3X1 g3051 (.Y(n_27),
	.C(n_21),
	.B(state[2]),
	.A(reset));
   INVX1 g3053 (.Y(n_26),
	.A(n_43));
   NAND2X1 g3056 (.Y(n_20),
	.B(n_39),
	.A(state[4]));
   NOR2X1 g3060 (.Y(n_18),
	.B(n_21),
	.A(state[7]));
   NAND2BX1 g3045 (.Y(n_31),
	.B(pin_success),
	.AN(n_57));
   NAND2X1 g3054 (.Y(n_43),
	.B(n_16),
	.A(n_15));
   NOR2BX1 g3055 (.Y(n_17),
	.B(n_15),
	.AN(n_16));
   INVXL g3071 (.Y(pin_process_init),
	.A(n_12));
   NOR3BX1 g3061 (.Y(n_49),
	.C(state[5]),
	.B(state[4]),
	.AN(state[9]));
   XNOR2X1 g3062 (.Y(n_11),
	.B(fail_counter[1]),
	.A(fail_counter[0]));
   NAND2X1 g3072 (.Y(n_12),
	.B(state[2]),
	.A(n_8));
   NOR2X1 g3077 (.Y(n_39),
	.B(n_37),
	.A(state[8]));
   NOR2XL g3076 (.Y(card_choice[0]),
	.B(n_15),
	.A(reset));
   AOI2BB1XL g3058 (.Y(n_65),
	.B0(visa_choice_in),
	.A1N(mastercard_choice_in),
	.A0N(amex_choice_in));
   AND2XL g3074 (.Y(process_abort),
	.B(state[0]),
	.A(n_8));
   AND2XL g3073 (.Y(pymt_amt_print),
	.B(state[3]),
	.A(n_8));
   NOR2XL g3069 (.Y(n_6),
	.B(pymt_amt_conf),
	.A(pymt_amt_denied));
   NAND2BX1 g3075 (.Y(n_21),
	.B(state[6]),
	.AN(state[0]));
   NOR2BX1 g3066 (.Y(light_bit),
	.B(reset),
	.AN(state[6]));
   NOR2X1 g3068 (.Y(n_14),
	.B(state[3]),
	.A(state[1]));
   NOR2X1 g3067 (.Y(n_16),
	.B(state[5]),
	.A(state[9]));
   NOR2XL g3063 (.Y(n_4),
	.B(transaction_fail),
	.A(transaction_success));
   NOR2BX1 g3065 (.Y(pymt_process_init),
	.B(reset),
	.AN(state[1]));
   NOR2BX1 g3070 (.Y(n_2),
	.B(mastercard_choice_in),
	.AN(amex_choice_in));
   AND2X1 g3078 (.Y(n_57),
	.B(fail_counter[0]),
	.A(fail_counter[1]));
   NOR2BX1 g3064 (.Y(card_choice[1]),
	.B(reset),
	.AN(state[5]));
   INVX1 g3082 (.Y(n_37),
	.A(state[7]));
   INVX1 g3079 (.Y(n_15),
	.A(state[4]));
   INVXL g3081 (.Y(n_8),
	.A(reset));
   NOR4BX1 g2 (.Y(n_112),
	.D(n_36),
	.C(n_113),
	.B(n_12),
	.AN(n_18));
   NAND2BX1 g3096 (.Y(n_113),
	.B(n_14),
	.AN(state[8]));
   OAI2BB1X1 g3097 (.Y(n_114),
	.B0(n_85),
	.A1N(n_57),
	.A0N(n_78));
endmodule

